server:
  port: 8080
spring:
  application:
    name: short-dns
  #Config db and h2.
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:short_dns;DATABASE_TO_UPPER=false;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;
    schema: classpath:db/schema-h2.sql
    username: root
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2-database
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
